# -*- coding: utf-8 -*-
"""basic.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JoBHMLgNzZZsk2E6U-yd62bvPDf5dJk
"""



print("Hello world")